plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "shuzi312"
email: yybingyybing@foxmail.com
description: ""
github:
  username: yybingyybing
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: blog
    client_id: a6fb73b3e790e234bab8
    client_secret: cc10aaff53a03d05ab2ee002dbf401dd7627c7a3

#url: "https://bit-ranger.github.io/blog"
#url: "http://localhost:4000/"
url: "http://yybingyybing.github.io"
#imgrepo: "https://bit-ranger.github.io/blog/static/img"
imgrepo: "http://yybingyybing.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

