plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css, gitalk.css]
      scripts : [gitment.js, post.js, gitalk.min.js]



title: "shuzi312"
email: yybingyybing@foxmail.com
description: ""
github:
  username: yybingyybing
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: 
    client_id: e3f03ff88087909e1dc4
    client_secret: d8c3df3635bfbb8b26be5f133c3196a2bc1c2799

gitalk:
    enable: true
    owner: yybingyybing
    repo: yybingyybing.github.io
    clientID: e3f03ff88087909e1dc4
    clientSecret: d8c3df3635bfbb8b26be5f133c3196a2bc1c2799
    admin: yybingyybing
#url: "https://bit-ranger.github.io/blog"
#url: "http://localhost:4000/"
url: "https://yybingyybing.github.io"
#imgrepo: "https://bit-ranger.github.io/blog/static/img"
imgrepo: "https://yybingyybing.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

